global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring_app'
    metrics_path: '/api/prometheus'
    basic_auth:
      username: ${PROMETHEUS_USER}
      password: ${PROMETHEUS_PASSWORD}
    static_configs:
      - targets: ['172.31.38.30:8080']

  - job_name: 'node_exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ '172.31.38.30:9100' ]