global:
  scrape_interval: 20s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'spring_app'
    metrics_path: '/api/prometheus'
    basic_auth:
      username: admin
      password: 12345678
    static_configs:
      - targets: ['app:8080']

  - job_name: 'node_exporter'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - '172.31.38.30:9100'

  - job_name: 'mysql_exporter'
    static_configs:
      - targets: ['host.docker.internal:9104']

# 마지막 줄 반드시 빈 줄로 EOF
